### ISSUE TITLE
Error in Spelling

### ISSUE THREAD

**Issue by therealnoof** [f5devcentral/access-labs#12]
Error in Line 2 spelling

Setup Lab Environment
To access your dedicated student lab environment, you will require a web browser and Remote Desktop Protocol (RDP) client software. The web browser will be used to access the Lab Training Portal. The RDP client will be used to connect to the Jump Host, where you will be able to access the BIG-IP management interfaces (HTTPS, SSH).

Click DEPLOYMENT located on the top left corner to display the environment

Click ACCESS next to jumpohost.f5lab.local

**Comment by yahshun** [comment]
Fixed in all intros
